framework:
    secret: '%env(APP_SECRET)%'

    session:
        name: 'BILEMOSESSID' 
        cookie_secure: auto 
        cookie_httponly: true

# Configuration pour l'environnement de test
when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
